// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonkeyFinances.Financas.Api.Data;

#nullable disable

namespace MonkeyFinances.Financas.Api.Migrations
{
    [DbContext(typeof(FinancasContext))]
    [Migration("20221005133928_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MonkeyFinances.Financas.Api.Models.Entities.FormaPagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("FormaPagamentos", (string)null);
                });

            modelBuilder.Entity("MonkeyFinances.Financas.Api.Models.Entities.Parcela", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdFormaPagamento")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdTransacao")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NumParcela")
                        .HasColumnType("int");

                    b.Property<int>("TotalParcelas")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdFormaPagamento");

                    b.ToTable("Parcelas", (string)null);
                });

            modelBuilder.Entity("MonkeyFinances.Financas.Api.Models.Entities.Tipo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Tipos", (string)null);
                });

            modelBuilder.Entity("MonkeyFinances.Financas.Api.Models.Entities.Transacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataTransacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("IdParcela")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdTipo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Valor")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("IdParcela")
                        .IsUnique();

                    b.HasIndex("IdTipo");

                    b.HasIndex("IdUser");

                    b.ToTable("Transacoes", (string)null);
                });

            modelBuilder.Entity("MonkeyFinances.Financas.Api.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("MonkeyFinances.Financas.Api.Models.Entities.Parcela", b =>
                {
                    b.HasOne("MonkeyFinances.Financas.Api.Models.Entities.FormaPagamento", "FormaPagamento")
                        .WithMany("Parcelas")
                        .HasForeignKey("IdFormaPagamento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormaPagamento");
                });

            modelBuilder.Entity("MonkeyFinances.Financas.Api.Models.Entities.Transacao", b =>
                {
                    b.HasOne("MonkeyFinances.Financas.Api.Models.Entities.Parcela", "Parcela")
                        .WithOne("Transacao")
                        .HasForeignKey("MonkeyFinances.Financas.Api.Models.Entities.Transacao", "IdParcela")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MonkeyFinances.Financas.Api.Models.Entities.Tipo", "Tipo")
                        .WithMany("Transacoes")
                        .HasForeignKey("IdTipo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MonkeyFinances.Financas.Api.Models.Entities.User", "User")
                        .WithMany("Transacoes")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parcela");

                    b.Navigation("Tipo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MonkeyFinances.Financas.Api.Models.Entities.FormaPagamento", b =>
                {
                    b.Navigation("Parcelas");
                });

            modelBuilder.Entity("MonkeyFinances.Financas.Api.Models.Entities.Parcela", b =>
                {
                    b.Navigation("Transacao")
                        .IsRequired();
                });

            modelBuilder.Entity("MonkeyFinances.Financas.Api.Models.Entities.Tipo", b =>
                {
                    b.Navigation("Transacoes");
                });

            modelBuilder.Entity("MonkeyFinances.Financas.Api.Models.Entities.User", b =>
                {
                    b.Navigation("Transacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
